import React from 'react';
import { render } from 'react-dom';
import { H2, H3, BulletWrapper, ImageDiv, SocialDiv, DownloadDiv, SocialButton, BulletDiv } from './../styles/styles';


const Terms = () => (
  <div>
    <div className="Terms">
      <div className="Terms-header">
        <H2>Terms</H2>
      </div>

      <div className="Terms-body">

        <H3>Terms and Conditions</H3>

        <P>The following sets out the terms and conditions for use of the Spark website, application and our services.</P>
        <P>Introduction<br/>The basics<br/>Access to the App<br/>Registering a Spark account<br/>What you are allowed to do<br/>What you are not allowed to do<br/>Intellectual property rights<br/>Review forums<br/>External links<br/>Your personal information<br/>Our service standards<br/>Our liability<br/>Suspension &amp; termination<br/>General<br/>Dispute Resolution<br/>Additional Terms Relating to Apple<br/>Definitions<br/>Contact us</p>

        <H4>1. Introduction</span><span id="u62156-45"> </span><span id="u62156-48"><br/><br/></span></H4>
        <P>1.1 These are the terms of use, including the terms and conditions of supply (Terms), for www.spark-app.net, app.spark-app.net and the Spark application. For the purposes of these Terms, both the website and application shall be referred to as the &quot;App&quot;. The App is operated by Wanna Enterprises Ltd trading as Spark (we, us and our). We are a limited company, registered in England. Our registered company number is 7934000, and our registered office is at 1 Neptune House, Moodkee St, London, UK, SE16 7AU. Our VAT registration number is 138597273.<br/><br/>1.2 Your use of the App and your Purchase of any of the Products offered via our App is subject to these Terms and by logging in to our App you agree to be bound by them. You should print a copy of these Terms for future reference. Use of your personal information submitted via this App is governed by our privacy policy.<br/><br/>1.3 We reserve the right to change these Terms from time to time by changing them on the App, although no such change will affect any Purchase you have already made with us. Your continued use of the App and any new Purchases will be bound by the new Terms. These Terms were last updated on July 12, 2016.<br/><br/>1.4 As a consumer, nothing in these Terms will prevent you or stop you from being able to enforce or receive the full benefit of your legal rights provided under general UK law (your &quot;non-excludable statutory rights&quot;). For more information, please contact your local Citizens Advice Bureau, phone numbers can be found on their national website at www.nacab.org.uk.<br/><br/>1.5 In these Terms we use various capitalised terms (they are &quot;defined&quot;). This means they have special meanings, found in the next-to-last section of these Terms.</p>
        <P>&nbsp;</p>
        <H4><span>2. The basics</span><span id="u62156-68"><br/><br/></span></h4>
        <P>2.1 To use the App and make any Purchases, you must be 18 or over. By continuing to use the App and agreeing to these Terms you are representing to us that you are 18 and we can rely on this representation.<br/><br/>2.2 The App and the Events offered on the App are only directed at people who access the App and make Purchases in the UK. We do not represent that any Events are suitable outside the UK and you should be careful to satisfy yourself of a Event's suitability to your circumstances (such as considering your travel arrangements to/from the event because unless this is expressly stated as part of the Event, it is not included as part of the Purchase). If you choose to use the App or make a Purchase outside the UK you do so at your own initiative.<br/><br/>2.3 We grant you a limited licence to use the App to access and use our services for your own personal and non-commercial use, provided that you comply fully with these Terms.<br/><br/>2.4 We reserve the right to prevent you using the App or making Purchases, however we will honour Purchases already made, unless you have not complied with these Terms or we are unable to because of circumstances outside our control. For more on this, please read below.</p>
        <H4>3. Access to the App</h4>
        <P>3.1 We cannot guarantee the continuous, uninterrupted or error-free operability of the App. There may be times when certain features, parts or content of the App, or the entire App, become unavailable (whether on a scheduled or unscheduled basis) or are modified, suspended or withdrawn by us, in our sole discretion, without notice to you. You agree that we will not be liable to you or to any third party for any unavailability, modification, suspension or withdrawal of the App, or any features, parts or content of the App.<br/><br/>3.2 We may change the format and content of the App from time to time. We reserve the right to modify, change, substitute or withdraw any Events or other information on our App. You agree that your use of the App is on an 'as is' and 'as available' basis and at your sole risk.</p>
        <h4>4. Registering a Spark account</h4>
        <P>4.1 Why register? To put simply, if you don't register an account, you won't be able to make any Purchases. This is because you need an account in order to view your Purchased Products, redeem them (if required), view your past Purchases, store your financial details and modify your preferences to name a few. We reserve the right to decline a new registration or cancel your account at any time (including if you don't provide us with a valid e-mail address that is personal to you, or if you don't provide us with a correct name and surname).<br/><br/>4.2 To register an account you will need to fill out a form on the mobile app or online. You warrant that the information you input is true, complete and accurate. You will promptly inform us of any changes to such information (you can do this by updated your account details at any time). The personal information you give us is governed by our privacy policy.<br/><br/>4.3 In order to register and access your account, you will need to choose a password. It is important you keep this password confidential because you are entirely responsible if you do not maintain the confidentiality of your password to a reasonably expected standard and Purchases are made via your account. Let us know as soon as you become aware there has been a breach of security and we will suspend your account. You agree that any person who you directly or implicitly permit to use your password (implicitly, for example, because you do not log out of your account and another person uses your device to make Purchases or you write your password on a noticeboard in your home and a family member then uses it to gain access to your account) is authorised to act as your agent to use the App and make Purchases via your account. You will not be responsible to pay for Purchases made after you have notified us of a password change or that security has been compromised.<br/><br/>4.4 One individual user is allowed to register only one account on the App. You warrant that you will not create fraudulent accounts. You also warrant that you will not use any fraudulent activities to generate unfair Reward Credits in the App to be applied to you (for instance, you will not redeem your own invitation code with a different account of yours).</p>
        <H4>5. What you are allowed to do</span><span id="u62156-113"><br/><br/></span></h4>
        <P>5.1 You may only use the App for non-commercial use and only in accordance with these Terms. You may retrieve and display content from the App on a computer or mobile device screen, print and copy individual pages and, subject to the next section, store such pages in electronic form. Additional terms may also apply to certain features, parts or content of the App and, where they apply, they will be displayed before you access the relevant features, parts or content.</p>
        <H4>6. What you are not allowed to do</span><span id="u62156-121"><br/><br/></span></h4>
        <P>6.1 Except to the extent expressly set out in these Terms, you are not allowed to:<br/>store pages of the App on a server or other storage device connected to a network or create an electronic database by systematically downloading and storing all or most of the pages of the App; or remove or change any content of the App or attempt to circumvent security or interfere with the proper working of the App or the servers on which it is hosted.</p>
        <P><br/>6.2 You must only use the App and anything available from the App for lawful purposes (complying with all applicable laws and regulations), in a responsible manner, and not in a way that might damage our name or reputation or that of any of our affiliates.<br/><br/>6.3 All rights granted to you under these Terms will terminate immediately in the event that you have not followed your responsibilities as required by them (legally known as a &quot;breach&quot;).</p>
        <P>&nbsp;</P>
        <H4>7. Content &amp; Privacy</span><span><br/><br/></span></H4>
        <P>7.1 You retain all your rights to any Content you submit, upload or display on or while using Spark. This means that you own all the Content you post and are responsible for its settings.</p>
        <P>&nbsp;</P>
        <P>7.2 Content will not show up in public search results on the Site and only Users you have given access will be able view the Content either in your albums or in search results.</p>
          <ul>
            <li>
             <ul>
              <li>Although we have created measures to protect your privacy, please be aware this does not mean that only the people you invite will see it. Users may still be able to find a photo or video through other search mechanisms, and then share or link to it outside the Site and/or App.</li>
             </ul>
            </li>
          </ul>
          <ul>
            <li>
             <ul>
              <li>Please remember, if you share Content from the Site or provide someone with a direct link to Content, others may be able to see it.<br/><br/></li>
             </ul>
            </li>
          </ul>
        <P>7.3 If you remove your Content from the Site, Spark will promptly hide it from search results on the Site; however, we might still have it stored in backup files or on servers, and we may retain it as needed. We are not responsible for sites that it was shared to before it was removed.</p>
        <P>&nbsp;</p>
        <P>7.4 By sharing content on Spark, you are also giving other Members on Spark the right to copy, distribute, publicly perform, publicly display, reproduce and create derivative works from it via the Site, third party websites or applications (for example, via services allowing Members to order prints of Content or t-shirts and similar items containing Content, and via social media websites), provided such use is not for a commercial purpose.</p>
        <P>&nbsp;</p>
        <P>7.5 By uploading, you are confirming that the Content is yours—no one else's—and that the uploading and use of your Content does not violate the privacy rights, publicity rights, copyrights, contract rights, intellectual property rights or human rights of somebody else. If we learn that you are infringing others' rights or are using Content that is not yours, Spark has the right to remove this Content and you agree that you are responsible for any costs associated with the infringement.</p>
        <P>&nbsp;</p>
        <P>7.6 Spark may manipulate your Content to offer the Spark Services (including transcoding and/or reformatting Content) to allow its use throughout the Spark Services.</p>
        <P>&nbsp;</p>
        <P>7.7 Spark has the right to place advertising, promotions, notifications or identifiers and watermarks on or near your Content, and how and what are up to us.</p>
        <P>&nbsp;</p>
        <P>7.8 Spark may moderate Content. However, we are not responsible for what you have uploaded and we are under no obligation to modify or remove any inappropriate Content.</p>
        <P>&nbsp;</p>
        <P>7.9 If you stop using the Spark Services, your Content may remain on the Site unless you actively remove your Content, and the rights you granted to us and other Users remain.</p>
        <P>&nbsp;</p>
        <P>7.10 In order to continue to improve the Site and Spark Services, we may use software and other things on the Site that we own or that have been licensed to us (&quot;Spark Software&quot;). Spark has also created the look, feel and architecture of the Site and has posted certain images and videos (&quot;Spark Content&quot;). Together the Spark Content and Spark Software are the &quot;Spark Materials.&quot; Spark Materials are ours and remain ours. Except in viewing the Site, you agree that you will not copy, distribute, publicly perform, publicly display, reproduce or create derivative works from the Spark Software. If you follow these Terms, you are entitled to use and display the Spark Content the same way you would use other Public Content on the Site.</p>
        <P>&nbsp;</p>
        <H4><span>8. Limits on Use</span><span><br/><br/></span></H4>
        <P>8.1 It is a violation of these Terms to disrupt the Site or the way it functions, interfere with other Users' enjoyment of the Site or Spark Services or use the Site to deceive, harass or solicit people.</p>
        <P>&nbsp;</p>
        <P>8.2 It is also a violation to scrape the Site, fusker files or otherwise make any use of data mining, robots or similar data gathering and extraction tools.</p>
        <P>&nbsp;</p>
        <P>8.3 It is up to Spark whether to terminate your use for violation of these prohibitions or similar activities.</p>
        <P>&nbsp;</p>
        <H4><span>9. Other Important Guidelines</span><span id="u62156-197"><br/><br/></span></h4>
        <P>9.1 You are solely responsible for your interactions with other Members. Nonetheless, we reserve the right, but are not obligated, to intervene for the benefit of the Site and Spark Services.</p>
        <P>&nbsp;</P>
        <P>9.2 These Terms and the Privacy Policy can change. Again, please carefully read this document and our other policies. We may announce if any &quot;big&quot; changes are made, but so long as you've used the Site after the change, regardless of any separate notice, you agree to the current posted version of the Terms.</p>
        <P>&nbsp;</p>
        <P>9.3 Our Site is hosted in the UK. There may be more or fewer protections for you in your country than here.</p>
        <P>&nbsp;</p>
        <P>9.4 Software available in connection with the Site and services offered through the Site (the &quot;Software&quot;) is further subject to United Kingdom export controls. No Software may be downloaded from the Spark Services or otherwise exported or re-exported in violation of U.K. export laws. Downloading or using the Software is at your sole risk.</p>
        <P>&nbsp;</p>
        <P>9.5 These Terms are governed by, and interpreted in keeping with, the laws of the United Kingdom, regardless of any conflict of law provisions. You and Spark agree to submit to the exclusive jurisdiction of the courts located within the United Kingdom to resolve any dispute arising out of the Agreement or the Spark Services.</p>
        <P>&nbsp;</p>
        <P>9.6 As a Member of Spark, if you become aware of misuse of the Spark Services by any person, please email support@spark-app.net with specific details.</p>
        <P>&nbsp;</p>
        <P>9.7 You use the Site at your own risk and the Site and services are provided &quot;AS IS.&quot;</p>
        <P>&nbsp;</p>
        <P>9.8 We are not saying that the Site will meet any of your specific needs or that you will get any particular results if you use the Site. We are not responsible for the conduct of other Users' conduct on- or off-line.</p>
        <P>&nbsp;</p>
        <P>9.9 We encourage you to always keep backups of your Content. Spark is not responsible if any of your Content is deleted, or if any modification, suspension or discontinuation of the Site or services causes you to lose any Content—even if you're a Paying Member.</p>
        <P>&nbsp;</p>
        <P>9.10 While we make an effort to keep the Site up and running at all times, we are not responsible for any errors, omissions, interruptions, deletions, defects, delays in operation or transmission, communications line failure, theft or destruction or unauthorized access to, or alteration of, any User communication, whether the result of our maintenance of the Site or any problems or technical malfunction of any network, servers, software or equipment, Internet traffic or any other failure of any nature.</p>
        <P>&nbsp;</p>
        <P>9.11 We are not responsible for advertisements or applications or services that are posted on or through the Site, nor do we have any responsibility for the goods or services provided by our advertisers or via other websites or applications, including our print vendor.</p>
        <P>&nbsp;</p>
        <P>9.12 The Site may contain links to other websites, wholly unrelated to Spark. For example, when you seek to print an image, you will be redirected to Spark's print vendor. If you enter the print site, or otherwise click on links to third party sites, you will be leaving the Site. When you do, you will be governed by the terms of use and privacy policy of that other site. You should review that site's terms and policies.</p>
        <P>&nbsp;</p>
        <P><span>10. Intellectual property rights</span><span><br/><br/></span></h4>
        <P>10.1 All intellectual property rights (which includes rights such as copyright, and rights in trade marks) in any content of the App (including text, graphics, software, photographs and other images, videos, sound, trade marks and logos) are owned by us and/or our licensors. Except as expressly set out in these Terms, nothing in these Terms gives you any rights in respect of any intellectual property owned by us or our licensors and you acknowledge that you do not acquire any ownership rights by downloading content from the App. If you print off, copy or store pages from the App (only as permitted by these terms and conditions), you must ensure that any copyright, trade mark or other intellectual property right notices contained in the original content are reproduced.<br/><br/>10.2 You agree that by submitting any posting, images or other content for publication on the App (Your Content), you retain any copyright you may have in Your Content, however you grant us and our affiliates a perpetual, irrevocable, worldwide, non-exclusive, royalty-free and fully sub-licensable right and licence to use, reproduce, edit, modify, adapt, publish, translate, create derivative works from, distribute, perform and display such content (in whole or in part) and/or to incorporate it into other works in any form, media or technology, whether for commercial or non-commercial purposes. You waive any moral rights you may have in, or to be identified as the author, of Your Content.<br/><br/>10.3 You are solely responsible for Your Content (including content you share with other sites, such as social networking sites) and we do not endorse Your Content or any opinion, recommendation, or advice expressed therein, and we expressly disclaim any and all liability in connection with Your Content.<br/><br/><br/></p>
        <H4><span>11. Review forums</span><span><br/><br/></span></h4>
        <P>11.1 The App may, from time to time, make message boards, news groups and/or other public forums (collectively Review Forums) available to you so that you can feedback on Products offered on the App and read the feedback submitted by other users of the App. We do not control the material submitted to Review Forums (collectively Postings), nor are Review Forums moderated. You are solely responsible for the content of your Postings as submitted by you and acknowledge that all Postings express the views of their respective authors, and not our views.<br/><br/>11.2 If you participate in any Review Forum, you must:<br/>keep all Postings relevant to the purpose of the Review Forum and the nature of any topic;<br/>not submit any Posting that is unlawful, threatening, abusive, libellous, pornographic, obscene, vulgar, indecent, offensive or which infringes on the intellectual property rights or other rights of any person;<br/>not submit any Posting that contains any viruses and/or other code that has contaminating or destructive elements;<br/>not submit any Posting containing any form of advertising; and<br/>not impersonate, or misrepresent an affiliation with, any person or entity.<br/>You agree that, by submitting any Posting, you grant us and our affiliates a perpetual, irrevocable, worldwide, non-exclusive, royalty-free and fully sub-licensable right and licence to use, reproduce, modify, adapt, publish, translate, create derivative works from, distribute, perform and display such Posting (in whole or part) and/or to incorporate it in other works in any form, media or technology, and you waive any moral rights you may have in, or to be identified as the author, of such Posting.<br/><br/>11.3 Whilst we do not screen or monitor Postings, we reserve the right, in our sole discretion, to delete, edit or modify any Posting submitted by you and/or to close any topic, at any time without notice to you.<br/><br/>11.4 Complaints about the content of any Posting must be sent to hello@spark-app. net and must contain details of the specific Posting giving rise to the complaint.<br/><br/></p>
        <H4><span>12. External links</span><span><br/><br/></span></h4>
        <P>12.1 The App may, from time to time, include links to external sites. We have included links to these sites to provide you with access to information and services that you may find useful or interesting. We are not responsible for the content of these sites or for anything provided by them and do not guarantee that they will be continuously available. The fact that we include links to such external sites does not imply any endorsement of or association with their operators.</p>
        <P>&nbsp;</p>
        <H4><span>13. Your personal information</span><span><br/><br/></span></h4>
        <P>13.1 Use of your personal information submitted via the App is governed by our privacy policy.</p>
        <P>&nbsp;</p>
        <H4><span>14. Our service standards</span><span><br/><br/></span></h4>
        <P>14.1 We warrant that we will exercise reasonable care and skill in performing our obligations under these Terms. Provided we have done so, we shall not be liable for errors or omissions.. In the event of an error or omission we will use reasonable endeavours to correct any errors or omissions as soon as reasonably practicable after we become aware.<br/><br/>14.2 Except as expressly stated in these Terms, all warranties, conditions or other terms, whether express or implied by statute or common law or otherwise are excluded to the fullest extent permitted by law. This does not stop you from exercising your legal rights under general law to the extent that we cannot lawfully exclude them, or claiming any remedies you might be entitled to under general law.</p>
        <P>&nbsp;</p>
        <H4><span>15. Our liability</span><span><br/><br/></span></h4>
        <P>15.1 Nothing in these Terms shall limit or exclude our liability to you:<br/>for death or personal injury caused by our negligence;<br/>for fraudulent misrepresentation;<br/>for breach of any obligations implied by section 12 of the Sale of Goods Act 1979 or section 2 of the Supply of Goods and Services Act 1982;<br/>under Part I of the Consumer Protection Act 1987; or<br/>for any other liability that may not, under English law, be limited or excluded.<br/><br/></p>
        <P>15.2 Subject to this, in no event shall we be liable to you for any business losses (and loss of profits shall always be treated as a type of business loss) and any liability we do have for losses you suffer arising from any Purchases shall not exceed 100% of the aggregate amount spent on the Purchase for the relevant Ticket(s). Further, our liability to you for any and all losses however they arise in connection with these Terms and your use of the App (including any Purchases) is strictly limited to losses that were reasonably foreseeable. Losses are foreseeable where they could be contemplated by you and us at the time your order is accepted by us.<br/><br/>15.3 Other than as expressly described in these Terms, Wanna Enterprises Ltd does not warrant and excludes all liability in respect of, or to provide, the Events for which Tickets may be redeemed, including in respect of the quality, safety, usability or any other aspect of the Events in respect of which a Ticket is or may be redeemed. We do, however, issue credits and refunds in limited circumstances (see section Our Refunds Policy).<br/><br/>15.4 We will not be liable or responsible for any failure to perform, or delay in performance of, any of our obligations that are caused by events outside our reasonable control.<br/><br/>15.5 Where videos are displayed they are intended to be purely representative of the artist or event. Your actual experience may vary.</p>
        <P>&nbsp;</p>
        <H4><span>16. Suspension and termination</span><span><br/><br/></span></h4>
        <P>16.1 We may suspend or terminate all or part of your use of the App and/or your account if you use (or permit anyone other than you to use) the App or your account in breach of these Terms and we do not reasonably consider that your breach can be resolved, or if it can be resolved you have failed to resolve it to our reasonable satisfaction after we have asked you to do so and given you a reasonable opportunity to do so.<br/><br/>16.2 Termination shall not prejudice any other right or remedy you or we may have in respect of accrued rights (including rights in respect of any breach) or liabilities which arose prior to termination.</p>
        <P>&nbsp;</p>
        <H4><span>17. General</span><span><br/><br/></span></h4>
        <P>17.1 These Terms are personal to you. You may not transfer or assign any or all of your rights or obligations under these Terms to any other person without our consent.<br/><br/>17.2 All notices given by you to us must be given in writing to the address set out at the end of these Terms. We may give notice to you at either the email or postal address you provide to us when placing an order.<br/><br/>17.3 If we fail to enforce any of our rights, it does not result in a waiver of that right.<br/><br/>17.4 If any provision of these Terms is found to be unenforceable, that provision shall be struck out and where capable all other provisions shall remain in force unaffected.<br/><br/>17.5 These Terms may not be varied except with our express written consent.<br/><br/>17.6 These Terms and any document expressly referred to in them constitute the entire agreement between you and us about the subject matter of these Terms and, in relation to such subject matter, supersedes and extinguishes all earlier understandings and agreements between you and us and all earlier representations by us, including any innocent or negligent misrepresentations. We do not limit our liability to you for any fraudulent misrepresentations made by us in these Terms or otherwise.<br/><br/>17.7 All provisions of these Terms apply equally to and are for the benefit of Wanna Enterprises Ltd, its group members (which means, in relation to Wanna Enterprises Ltd, any &quot;group undertaking&quot; as defined in section 1161 of the Companies Act) and the Merchants at any relevant time and each shall have the right to enforce such provisions directly or on its own behalf (save that these Terms may be varied or rescinded without the consent of the group members and the Merchants). Subject to the previous sentence, no term of this Agreement is otherwise enforceable pursuant to the Contracts (Rights of Third Parties) Act 1999 by any person who is not a party to it.<br/><br/>17.8 These Terms (and all non-contractual relationships between you and us) shall be governed by English law, and you agree that any dispute between you and us regarding them or any Purchase will only be dealt with by the nearest courts in England and Wales (nearest to where you reside).</p>
        <P>&nbsp;</p>
        <H4><span id="u62156-379">18. Dispute Resolution</span><span id="u62156-382"><br/><br/></span></h4>
        <P>18.1 In the first instance we request that you Contact Us if you have a complaint against us and we shall try to resolve it.</p>
        <P>&nbsp;</p>
        <H4><span id="u62156-387">19. Additional terms relating to Apple</span><span id="u62156-390"><br/><br/></span></h4>
        <P>If you download, access and/or use the App on Apple’s iOS operating system:<br/><br/>19.1 The App may only be accessed and used on a device owned or controlled by you and using Apple’s iOS operating system, and only in accordance with Apple’s usage rules published in its App Store terms of service;<br/><br/>19.2 You acknowledge and agree that:<br/><br/>a) Apple has no obligation at all to provide any support or maintenance services in relation to the App. If you have any maintenance or support questions in relation to the App, please Contact Us, not Apple, using the details in these Terms;<br/><br/>b) Except as otherwise expressly set out in these Terms, any claims relating to the possession or use of the App are between you and us (and not between you, or anyone else, and Apple);<br/><br/>c) In the event of any claim by a third party that your possession or use (in accordance with these Terms) of the App infringes any intellectual property rights, Apple will not be responsible or liable to you in relation to that claim; and<br/><br/>d) Although these Terms are entered into between you and us (and not Apple), Apple, as a third party beneficiary under these Terms, will have the right to enforce these Terms against you;<br/><br/>19.3 You represent and warrant that:<br/><br/>a) You are not, and will not be, located in any country that is the subject of a United States Government embargo or that has been designated by the United States Government as a &quot;terrorist supporting&quot; country; and<br/><br/>b) You are not listed on any United States Government list of prohibited or restricted parties; and<br/><br/>19.4 If the App does not conform to any warranty applying to it, you may notify Apple, which will then refund the purchase price of the App (if any) to you. Subject to that, and to the maximum extent permitted by law, Apple does not give or enter into any warranty, condition or other term in relation to the App and will not be liable to you for any claims, losses, costs or expenses of whatever nature in relation to the App or as a result of you or anyone else using the App or relying on any of its content.</p>
        <P>&nbsp;</p>
        <H4><span id="u62156-425">20. Definitions</span><span id="u62156-428"><br/><br/></span></h4>
        <P>&quot;Merchant&quot; means a third party partner of Spark who sells the events and services for which a Purchase can be made.<br/><br/>&quot;Purchase&quot; or &quot;Purchased&quot; means the purchase of a Product.<br/><br/>&quot;Ticket&quot; means a ticket for a particular Event from a Merchant, which is subject to any additional terms of entry set by the Merchant.<br/><br/>&quot;Events&quot; means the events and/or services offered by a particular Merchant for which a Purchase can be made.</p>
        <P>&nbsp;</p>
        <H4><span id="u62156-442">21. Contact Us</span><span id="u62156-445"><br/><br/></span></h4>
        <P>Please submit any questions you have about these Terms, an order you have placed or purchasing in general by email to hello@spark-app.net or write to us at:<br/><br/>Spark<br/>1 Neptune House<br/>Moodkee St<br/>London<br/>SE16 7AU.</p>

      </div>

    </div>
  </div>
);

export default Terms;
